// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bshw_theta_integrals_cpp
ComplexVector bshw_theta_integrals_cpp(NumericVector u, double lambda, NumericVector theta, NumericVector exp_neg, double step_size);
RcppExport SEXP _CompFinanceR_bshw_theta_integrals_cpp(SEXP uSEXP, SEXP lambdaSEXP, SEXP thetaSEXP, SEXP exp_negSEXP, SEXP step_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type exp_neg(exp_negSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(bshw_theta_integrals_cpp(u, lambda, theta, exp_neg, step_size));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_short_rate_paths_cpp
List gaussian_short_rate_paths_cpp(NumericMatrix shocks, NumericVector theta, NumericVector initial_rate, double mean_reversion, double dt);
RcppExport SEXP _CompFinanceR_gaussian_short_rate_paths_cpp(SEXP shocksSEXP, SEXP thetaSEXP, SEXP initial_rateSEXP, SEXP mean_reversionSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type shocks(shocksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_rate(initial_rateSEXP);
    Rcpp::traits::input_parameter< double >::type mean_reversion(mean_reversionSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_short_rate_paths_cpp(shocks, theta, initial_rate, mean_reversion, dt));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_measure_switch_cpp
List gaussian_measure_switch_cpp(NumericMatrix shocks, NumericVector theta, NumericVector initial_rate, double mean_reversion, double volatility, double dt, NumericVector lambda);
RcppExport SEXP _CompFinanceR_gaussian_measure_switch_cpp(SEXP shocksSEXP, SEXP thetaSEXP, SEXP initial_rateSEXP, SEXP mean_reversionSEXP, SEXP volatilitySEXP, SEXP dtSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type shocks(shocksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_rate(initial_rateSEXP);
    Rcpp::traits::input_parameter< double >::type mean_reversion(mean_reversionSEXP);
    Rcpp::traits::input_parameter< double >::type volatility(volatilitySEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_measure_switch_cpp(shocks, theta, initial_rate, mean_reversion, volatility, dt, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pathwise_delta_cpp
NumericVector pathwise_delta_cpp(NumericVector terminal_prices, NumericVector strikes, double initial_price, double discount_factor, double sign_multiplier, bool is_call);
RcppExport SEXP _CompFinanceR_pathwise_delta_cpp(SEXP terminal_pricesSEXP, SEXP strikesSEXP, SEXP initial_priceSEXP, SEXP discount_factorSEXP, SEXP sign_multiplierSEXP, SEXP is_callSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type terminal_prices(terminal_pricesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type strikes(strikesSEXP);
    Rcpp::traits::input_parameter< double >::type initial_price(initial_priceSEXP);
    Rcpp::traits::input_parameter< double >::type discount_factor(discount_factorSEXP);
    Rcpp::traits::input_parameter< double >::type sign_multiplier(sign_multiplierSEXP);
    Rcpp::traits::input_parameter< bool >::type is_call(is_callSEXP);
    rcpp_result_gen = Rcpp::wrap(pathwise_delta_cpp(terminal_prices, strikes, initial_price, discount_factor, sign_multiplier, is_call));
    return rcpp_result_gen;
END_RCPP
}
// pathwise_vega_cpp
NumericVector pathwise_vega_cpp(NumericVector terminal_prices, NumericVector adjustment, NumericVector strikes, double volatility, double discount_factor, double sign_multiplier, bool is_call);
RcppExport SEXP _CompFinanceR_pathwise_vega_cpp(SEXP terminal_pricesSEXP, SEXP adjustmentSEXP, SEXP strikesSEXP, SEXP volatilitySEXP, SEXP discount_factorSEXP, SEXP sign_multiplierSEXP, SEXP is_callSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type terminal_prices(terminal_pricesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjustment(adjustmentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type strikes(strikesSEXP);
    Rcpp::traits::input_parameter< double >::type volatility(volatilitySEXP);
    Rcpp::traits::input_parameter< double >::type discount_factor(discount_factorSEXP);
    Rcpp::traits::input_parameter< double >::type sign_multiplier(sign_multiplierSEXP);
    Rcpp::traits::input_parameter< bool >::type is_call(is_callSEXP);
    rcpp_result_gen = Rcpp::wrap(pathwise_vega_cpp(terminal_prices, adjustment, strikes, volatility, discount_factor, sign_multiplier, is_call));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CompFinanceR_bshw_theta_integrals_cpp", (DL_FUNC) &_CompFinanceR_bshw_theta_integrals_cpp, 5},
    {"_CompFinanceR_gaussian_short_rate_paths_cpp", (DL_FUNC) &_CompFinanceR_gaussian_short_rate_paths_cpp, 5},
    {"_CompFinanceR_gaussian_measure_switch_cpp", (DL_FUNC) &_CompFinanceR_gaussian_measure_switch_cpp, 7},
    {"_CompFinanceR_pathwise_delta_cpp", (DL_FUNC) &_CompFinanceR_pathwise_delta_cpp, 6},
    {"_CompFinanceR_pathwise_vega_cpp", (DL_FUNC) &_CompFinanceR_pathwise_vega_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_CompFinanceR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
